### ISSUE TITLE
what about adding a tunneling feature for more control and monitoring if everything is going as it should ?

### ISSUE THREAD

**Issue by minanagehsalalma** [rstenvi/DNSrebinder#1]
just like what he wanted to do in the to do list in this article 
https://sinister.ly/Thread-DNS-Rebinding-Attack

> I need to make a tunnel (using JavaScript) to gain more control!

**Comment by minanagehsalalma** [comment]
@rstenvi just like this 

https://portswigger.net/daily-swig/new-tool-enables-dns-rebinding-tunnel-attacks-without-reconnaissance

https://youtu.be/sqUxeiqq0xE

**Comment by rstenvi** [comment]
I'm not planning to work on this project anymore. Feel free to fork it and create your own tool.
